## Data-driven conformance runner for Clay's flat-container protocol.
##
## Expected rectangles are generated by the standalone Clay oracle. This
## module turns the same case description into Roclay values and interprets
## final placement callbacks into a list for comparison.
import geometry.Geometry2d
import roclay.Roclay
import RoclayRecording

RoclayFlatConformance := [].{

	Align := [AlignStart, AlignCenter, AlignEnd]

	FlatChild : {
		intrinsic : Roclay.Size,
		sizing : Roclay.Sizing,
		aspect_ratio : [Some(Roclay.Scalar), None],
	}

	FlatCase : {
		direction : Roclay.Direction,
		padding : Roclay.Insets,
		gap : Roclay.Scalar,
		align_x : Align,
		align_y : Align,
		root_size : Roclay.Size,
		children : List(FlatChild),
		expected : List(Roclay.Rect),
	}

	Recording : RoclayRecording.Recording(Roclay.Rect)

	record : Roclay.Place(Recording)
	record = |placement| RoclayRecording.one(placement.rect)

	main_align : Align -> Roclay.MainAlign
	main_align = |align| match align {
		AlignStart => MainStart
		AlignCenter => MainCenter
		AlignEnd => MainEnd
	}

	cross_align : Align -> Roclay.CrossAlign
	cross_align = |align| match align {
		AlignStart => CrossStart
		AlignCenter => CrossCenter
		AlignEnd => CrossEnd
	}

	child_layout : FlatChild -> Roclay.Layout(Recording)
	child_layout = |child| {
		base = Roclay.sized(child.sizing, Roclay.leaf(child.intrinsic, RoclayFlatConformance.record))
		match child.aspect_ratio {
			Some(ratio) => Roclay.aspect_ratio(ratio, base)
			None => base
		}
	}

	layout : FlatCase -> Roclay.Layout(Recording)
	layout = |case| {
		var $children = []
		for child in case.children {
			$children = List.append($children, RoclayFlatConformance.child_layout(child))
		}
		(resolved_main_align, resolved_cross_align) = match case.direction {
			LeftToRight => (RoclayFlatConformance.main_align(case.align_x), RoclayFlatConformance.cross_align(case.align_y))
			TopToBottom => (RoclayFlatConformance.main_align(case.align_y), RoclayFlatConformance.cross_align(case.align_x))
		}
		config = {
			..Roclay.default_box,
			direction: case.direction,
			padding: case.padding,
			gap: case.gap,
			sizing: { width: Fixed(case.root_size.width), height: Fixed(case.root_size.height) },
			main_align: resolved_main_align,
			cross_align: resolved_cross_align,
		}
		Roclay.before(RoclayFlatConformance.record, Roclay.box(config, $children))
	}

	actual! : FlatCase => List(Roclay.Rect)
	actual! = |case| {
		placement = Geometry2d.root_placement(Geometry2d.rect(0, 0, case.root_size.width, case.root_size.height))
		(Roclay.place!(RoclayFlatConformance.layout(case), placement)).items
	}

	near : Roclay.Scalar, Roclay.Scalar -> Bool
	near = |expected, actual| F32.abs(expected - actual) < 0.05

	near_rect : Roclay.Rect, Roclay.Rect -> Bool
	near_rect = |expected, actual| {
		RoclayFlatConformance.near(expected.x, actual.x) and
			RoclayFlatConformance.near(expected.y, actual.y) and
				RoclayFlatConformance.near(expected.width, actual.width) and
					RoclayFlatConformance.near(expected.height, actual.height)
	}

	matches! : FlatCase => Bool
	matches! = |case| {
		actual = RoclayFlatConformance.actual!(case)
		if List.len(actual) != List.len(case.expected) {
			Bool.False
		} else {
			var $same = Bool.True
			var $index = 0
			for actual_rect in actual {
				match List.get(case.expected, $index) {
					Ok(expected_rect) => if !(RoclayFlatConformance.near_rect(expected_rect, actual_rect)) {
						$same = Bool.False
					}
					Err(_) => {
						$same = Bool.False
					}
				}
				$index = $index + 1
			}
			$same
		}
	}

	first_failure! : List(FlatCase) => I32
	first_failure! = |cases| {
		var $failure = 0
		var $case_number = 1
		for case in cases {
			if $failure == 0 and !(RoclayFlatConformance.matches!(case)) {
				$failure = $case_number
			}
			$case_number = $case_number + 1
		}
		$failure
	}
}
