#!/usr/bin/env python3
"""Generate deterministic Roclay text cases with Clay expectations."""

from __future__ import annotations

import argparse
import random
import subprocess
from dataclasses import dataclass
from pathlib import Path

from generate_flat_conformance import number, parse_oracle


@dataclass(frozen=True)
class TextCase:
    name: str
    root_width: int
    root_height: int
    wrap_mode: int
    align: int
    font_size: int
    line_height: int
    lines: tuple[tuple[int, ...], ...]

    @property
    def text(self) -> str:
        return "\n".join(" ".join("x" * length for length in line) for line in self.lines)


def generate_case(rng: random.Random, index: int) -> TextCase:
    wrap_mode = rng.randint(0, 2)
    font_size = rng.randint(1, 5)
    line_count = rng.randint(1, 4) if wrap_mode == 1 else 1
    lines = tuple(
        tuple(rng.randint(1, 20) for _ in range(rng.randint(1, 8)))
        for _ in range(line_count)
    )
    return TextCase(
        name=f"text{index:04d}",
        root_width=rng.randint(1, 60),
        root_height=rng.randint(1, 80),
        wrap_mode=wrap_mode,
        align=rng.randint(0, 2),
        font_size=font_size,
        line_height=0 if rng.randint(1, 4) <= 3 else rng.randint(1, font_size * 3),
        lines=lines,
    )


def wire_case(case: TextCase) -> str:
    payload = [
        case.name,
        str(case.root_width),
        str(case.root_height),
        str(case.wrap_mode),
        str(case.align),
        str(case.font_size),
        str(case.line_height),
        str(len(case.lines)),
    ]
    for line in case.lines:
        payload.extend([str(len(line)), *(str(length) for length in line)])
    return " ".join(payload)


def roc_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def roc_rect(values: tuple[float, float, float, float]) -> str:
    return "Geometry2d.rect(" + ", ".join(number(value) for value in values) + ")"


def generate_source(
    cases: list[TextCase],
    expected: dict[str, list[tuple[str, tuple[float, float, float, float]]]],
    seed: int,
) -> str:
    wraps = ("TextWrapWords", "TextWrapNewlines", "TextWrapNone")
    aligns = ("TextAlignStart", "TextAlignCenter", "TextAlignEnd")
    lines = [
        'app [main!] { test_host: platform "../../test-platform/main.roc", geometry: "../../geometry/main.roc", roclay: "../../roclay/main.roc", conformance: "./main.roc" }',
        "",
        "# Generated by tools/generate_text_conformance.py; do not edit.",
        f"# seed={seed} cases={len(cases)}",
        "import geometry.Geometry2d",
        "import roclay.Roclay",
        "import conformance.RoclayTextConformance",
        "import test_host.TestDebug",
        "",
        "cases : List(RoclayTextConformance.TextCase)",
        "cases = [",
    ]
    for index, case in enumerate(cases, start=1):
        rows = expected[case.name]
        if not rows or rows[0][0] != "root" or any(
            name != f"text{text_index}" for text_index, (name, _rect) in enumerate(rows[1:])
        ):
            raise RuntimeError(f"unexpected Clay rows for {case.name}: {[name for name, _ in rows]}")
        rects = ", ".join(roc_rect(rect) for _name, rect in rows)
        line_height = "None" if case.line_height == 0 else f"Some({case.line_height})"
        lines.extend(
            [
                f"\t# case {index}: {case.name}",
                "\t{",
                f"\t\troot_size: Geometry2d.size({case.root_width}, {case.root_height}),",
                f"\t\ttext: {roc_string(case.text)},",
                f"\t\tfont_size: {case.font_size},",
                f"\t\tline_height: {line_height},",
                f"\t\twrap_mode: {wraps[case.wrap_mode]},",
                f"\t\talign: {aligns[case.align]},",
                f"\t\texpected: [{rects}],",
                "\t},",
            ]
        )
    lines.extend(
        [
            "]",
            "",
            "run! : List(RoclayTextConformance.TextCase) => I32",
            "run! = |all_cases| {",
            "\tvar $failure = 0",
            "\tvar $case_number = 1",
            "\tfor case in all_cases {",
            "\t\tif $failure == 0 and !(RoclayTextConformance.matches!(case)) {",
            "\t\t\tTestDebug.case!($case_number)",
            "\t\t\tfor rect in case.expected {",
            "\t\t\t\tTestDebug.expected_rect!(rect.x, rect.y, rect.width, rect.height)",
            "\t\t\t}",
            "\t\t\tfor rect in RoclayTextConformance.actual!(case) {",
            "\t\t\t\tTestDebug.actual_rect!(rect.x, rect.y, rect.width, rect.height)",
            "\t\t\t}",
            "\t\t\t$failure = $case_number",
            "\t\t}",
            "\t\t$case_number = $case_number + 1",
            "\t}",
            "\t$failure",
            "}",
            "",
            "main! = || run!(cases)",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--oracle", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--corpus-output", type=Path, required=True)
    parser.add_argument("--cases", type=int, default=250)
    parser.add_argument("--seed", type=int, default=0x54455854434C4159)
    args = parser.parse_args()

    if args.cases < 1 or args.cases > 2000:
        parser.error("--cases must be between 1 and 2000")

    rng = random.Random(args.seed)
    cases = [generate_case(rng, index) for index in range(args.cases)]
    corpus = "\n".join(wire_case(case) for case in cases) + "\n"
    completed = subprocess.run(
        [str(args.oracle), "--text-stdin"],
        input=corpus,
        text=True,
        capture_output=True,
        check=True,
    )
    expected = parse_oracle(completed.stdout)
    missing = [case.name for case in cases if case.name not in expected]
    if missing:
        raise RuntimeError(f"Clay returned no rows for: {missing}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.corpus_output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate_source(cases, expected, args.seed), encoding="utf-8")
    args.corpus_output.write_text(corpus, encoding="utf-8")


if __name__ == "__main__":
    main()
